### ISSUE TITLE
Reservation Availability Request mapped to the wrong function

### ISSUE THREAD

**Issue by oblassers** [IdealChain/sese2015#4]
When requesting the availability of a room for a certain date.
E.g. curl -X GET "http://localhost:8080/api/reservation?roomid=1&startdate=2015-12-12&enddate=2015-12-15" -H "X-Auth-Token: $(cat lua/authtoken)"

the request is mapped to "List<Reservation> getAllReservations(Long customerid)"
instead of "String isAvailableForReservation(Long roomId, Date startDate, Date endDate)

**Comment by fabthe** [comment]
@oblassers: Acknowledged, thanks. However: is this endpoint relevant for you? It doesn't seem to fit in anyway, so I would have removed it. 

In case this is for the task "Zimmerverwaltung backend" I may recommend something like this:
http://localhost:8080/api/reservation?roomid=123
You could do this, be extending the "List getAllReservations(Long customerid)" to "List getAllReservations(Long customerid, Long roomid)" and check inside the method for not-null parameters. I would then support to filter by customerid XOR roomid only, in order to keep logic and (h/s)ql queries reasonable.

**Comment by fabthe** [comment]
@oblassers removing the isAvailable endpoint doesn't seem to break anything in master. I will remove it and commit/push.
